blank_issues_enabled: false
contact_links:
  # TODO(Neverheard Studio): link to the Glide download page once one exists.

  - name: GitHub Discussions
    url: https://github.com/localsend/localsend/discussions
    about: If you think your issue isn't that serious, you can discuss it here

  - name: Contributing guide
    url: https://github.com/localsend/localsend/blob/main/CONTRIBUTING.md
    about: Check our contributing guide if you’re interested or have time

