display_name: Glide
# TODO(Neverheard Studio): replace with a real packager contact.
packager: Neverheard Studio
packagerEmail: hello@neverheard.studio
# TODO(Neverheard Studio): supply a real project URL once one exists.
buildArch: x86_64
license: MIT

icon: assets/packaging/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: An open source cross-platform alternative to AirDrop
summary: Share files easily with Glide
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
